### ISSUE TITLE
Linear to Slog3 not working properly

### ISSUE THREAD

**Issue by groucho86** [EleonoreMizo/fmtconv#12]
Hello,
I have a SGamut3.Cine Linear EXR. It seems like the Linear to Slog3 conversion is clipping in the highlights.

```
import vapoursynth as vs
import muvsfunc
core = vs.get_core()

input_path = 'source_sgamut

c = core.imwri.Read(input_path,float_output=True)
c = core.fmtc.transfer (clip=c, transs='linear', transd='slog3')
c.set_output()
```

I'm attaching:
source_sgamut3cine_linear.exr <-- source file
resolve_delinearized.tif <-- expected result
vs_delinearized.png <-- fmtconv result

[linear_to_slog3_tb.zip](https://github.com/EleonoreMizo/fmtconv/files/3691493/linear_to_slog3_tb.zip)

**Comment by EleonoreMizo** [comment]
Indeed.
This should be fixed with the r21 release.
