### ISSUE TITLE
r22 fails to build on FreeBSD: /usr/bin/ld: cannot find -latomic

### ISSUE THREAD

**Issue by jbeich** [EleonoreMizo/fmtconv#13]
FreeBSD uses Clang by default, so libatomic is often neither installed nor picked up from GCC-specific prefix. See [error log](https://github.com/EleonoreMizo/fmtconv/files/3951601/vapoursynth-fmtconv-r22.log) and [bug 230888](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230888). Removing `-latomic` helps to unbreak on x86 architectures.

**Comment by EleonoreMizo** [comment]
OK, thanks for the log. It seems we need -latomic only for some versions of GCC < 5.3. I’ll make a conditional.

**Comment by jbeich** [comment]
[Builds fine](https://github.com/EleonoreMizo/fmtconv/files/3984898/vapoursynth-fmtconv-r22.5.log) after 5e0340d35e4d.
