### ISSUE TITLE
fmtc.bitdepth(bits=14) does not work

### ISSUE THREAD

**Issue by theChaosCoder** [EleonoreMizo/fmtconv#16]
> Supported input formats:
> 
> 8-–12-, 14- and 16-bit integer.
> 32-bit floating point.
> Any planar colorspace.

But this does not work `clip = clip.fmtc.bitdepth(bits=14)`
This error is shown `vapoursynth.Error: bitdepth: output pixel bitdepth not supported.`

Maybe in the condition  "res == 14" was forgotten?
https://github.com/EleonoreMizo/fmtconv/blob/3b64292dd2741b819886f7896fb8f20e356dda1b/src/fmtc/Bitdepth.cpp#L145-L152

**Comment by EleonoreMizo** [comment]
This is normal. 14-bit format is supported for input but not for output. Do your really need 14-bit output? I try to avoid multiplying cases, as it makes the maintenance more complex and difficult.

**Comment by theChaosCoder** [comment]
Nope, I don't need it. I just thought it could be a "bug".
