### ISSUE TITLE
Matrix col_fam and the cm* constants in future VS versions

### ISSUE THREAD

**Issue by myrsloik** [EleonoreMizo/fmtconv#22]
I changed most of the constant values in the new version of the VS API but due to how things are structured filters that use the cm* (cmRGB, cmYUV...) constants from a different API version may leak through. Since fmtconv's matrix filter is the only external one that uses these constants it's probably easier to ask you to implement the workaround than to inspect and manipulate all the arguments whenever you filter is invoked.

Basically you need to check against both the API3 and API4 values. Here's how ShufflePlanes does it:
https://github.com/vapoursynth/vapoursynth/blob/doodle1/src/core/simplefilters.cpp#L561

Note that in the new version YCoCg has been removed as a separate format and is now considered to be "YUV". The experimental new builds can be found here:
https://forum.doom9.org/showthread.php?t=183070 

A longer summary of the issue here:
https://github.com/vapoursynth/vapoursynth/issues/726

**Comment by EleonoreMizo** [comment]
Thank you for letting me know the issue. I’m going to check this more deeply and find a workaround. But first I hope I could find a way to install recent VS versions, because Python 3.9 cannot be installed on Win 7.

**Comment by myrsloik** [comment]
I think it's easier to stay on R52 for now if you need to use Python 3.8. R53 and R54 were mostly Linux fixes anyway. If you manage to find a large number of upset users maybe I'll provide python 3.8 compatible builds. Or think of some way to support multiple python versions at once.

**Comment by EleonoreMizo** [comment]
Fixed in 67dab4adc11b11962c4f0c18dc4b45e5e8c974c4
I now include a small wrapping file that adds the v4 constants, instead of directly including `VapourSynth.h`.
