### ISSUE TITLE
Matrix will raise error when convert between RGB and OPP

### ISSUE THREAD

**Issue by vxzms** [EleonoreMizo/fmtconv#26]
Matrix will raise `matrix: unsupported color family for output.` when convert between RGB and OPP, like https://github.com/AmusementClub/mvsfunc/blob/mod/mvsfunc.py#L467 and https://github.com/AmusementClub/mvsfunc/blob/mod/mvsfunc.py#L688

**Comment by EleonoreMizo** [comment]
Thanks for the report. Fixed in 1453c2fae3a09b79748e2ecc04cbcd3cf59f2af2 for the next release.
