### ISSUE TITLE
Feature request: convert  YV12 interlaced <--> YV12 progressive

### ISSUE THREAD

**Issue by tvasenin** [EleonoreMizo/fmtconv#29]
Use case: DVD with progressive content encoded as interlaced YV12 and telecined.

After IVTC I end up with interlaced YV12, but want to treat the picture as progressive.

Currently, the only option is to assume the frame as progressive and live with slightly off chroma.

This request is minor, but the use case itself is quite popular :)

**Comment by EleonoreMizo** [comment]
I’m not sure to understand: IVTC should give you progressive YV12 pictures, right? This is the purpose of inverse telecine. And “MPEG-2” chroma placement is identical for interlaced and progressive content. Have you some example showing such a chroma issue?

**Comment by EleonoreMizo** [comment]
If it is encoded as interlaced (boths fields are considered as distinct pictures), the video may suffer from halved vertical resolution and slight chroma combing when the video is heavily compressed or in case of fast motion. You may need a specific anti-aliasing function like daa3 and process only the chroma planes. But the chroma should be located correctly anyway, and there is not setting in `fmtc.resample` that is missing here.
