### ISSUE TITLE
recipe for target '../../src/fmtcl/libavx2_la-TransLut_avx2.lo' failed

### ISSUE THREAD

**Issue by Selur** [EleonoreMizo/fmtconv#34]
trying to build current git I get the above error, see full log:
[fmtconv.log](https://github.com/EleonoreMizo/fmtconv/files/8879724/fmtconv.log)
same happens when using r29.
Is it a bug or am I missing something?

Thanks!
(not sure it's relevant, I'm using Vapoursynth R59)

**Comment by EleonoreMizo** [comment]
Thanks for the report. I tried to fix it in 0adef1c811c5715077448c41997d7ece116232d6. Does this work better?

**Comment by Selur** [comment]
Works again! Thanks!
