### ISSUE TITLE
Build Errors and Warnings on OS X (10.11) (gcc5)

### ISSUE THREAD

**Issue by jstnthrstpdsr** [EleonoreMizo/fmtconv#6]
**_Update**: Successfully built it now with gcc-4.9 (still: "OS-X-native" building would be nice)
_-----
When building fmtconv r17 on  a Mac (OS X 10.11.3) make fails with three errors (and a lot of warnings):

1. `In file included from ./../../src/conc/Interlocked.h:132:
./../../src/conc/Interlocked.hpp:268:16: error: invalid lvalue in asm input for
      constraint 'm'
        : [excg] "m" (&excg)
                      ^~~~~`

2. `In file included from ./../../src/conc/Interlocked.h:132:
./../../src/conc/Interlocked.hpp:312:16: error: invalid lvalue in asm input for
      constraint 'm'
        : [old]  "m" (&old)
                      ^~~~`
I've worked around this by simply removing the &-references in both blocks - but I do not really know what I was doing there and it most likely broke something.

3. For TransLut.cpp to compile on a Mac another include is needed:
`#include <cstdlib>`
Else, a `call to 'abs' is ambiguous` error gets thrown for line 350
(`		const int      ind_3     = std::abs (ind_2) - 1;`)
I've googled this one [https://stackoverflow.com/questions/30084577/ambiguous-call-to-abs](url). Maybe there's another way.

4. A whole lot of warnings like this one were thrown but didn't break the build process:
`warning: reference cannot be bound to
      dereferenced null pointer in well-defined C++ code; comparison may be
      assumed to always evaluate to true [-Wtautological-undefined-compare]
        assert (&dst1 != 0)`

5. And `make install` was complaining:
`make: *** No rule to make target `../../src/fmtc/Matrix_avx2.cpp', needed by `../../src/fmtc/libavx2_la-Matrix_avx2.lo'.  Stop.`
I believe I got around that ("avx issues? Like discussed for Linux at doom9?) by building from within Xcode and setting some platform specifics for the release build but again I didn't actually know what I was doing. It's just that I was hoping to somehow get havsfunc to work on my Mac. I did not succeed yet...  ;)

Would be great if a next / future releases would cross another platform border. :)

**Comment by EleonoreMizo** [comment]
Thanks for your report. BTW it’s better to report on the Doom9 thread because I almost never log in or even check the github pages.

1. 2. I tried to fix it my latest commit. Because I cannot test it, I’m not sure if it works better. At least it still compile with GCC on Cygwin.

3. Already fixed

4. Currently I cannot even compile fmtconv with clang because std::mutex is not supported on Cygwin yet, but I’ll see if I can do something. In the mean time you can mute the warning, it is harmless.

5. There is no Matrix_avx2.cpp anymore (replaced by fmtcl/MatrixProc_avx2.cpp), try to rebuild fmtconv with a more recent source tree.

**Comment by myrsloik** [comment]
I tested master as of today using latest osx, xcode and clang. It compiles (obviously shitloads of warnings). Using gcc isn't even what I'd consider "OS-X-native" since apple has made it very clear that clang is their favorite.

**Comment by jstnthrstpdsr** [comment]
I went for GCC 'cause with os-x-native tools I had no luck at all. 

Anyway, with the latest changes fmtconv did build (with GCC); haven't tried the native way. So - thanks for the update. And I might also try a "native" build.
