### ISSUE TITLE
Feature Request, High Dynamic Range Video Conversion

### ISSUE THREAD

**Issue by J1Man** [EleonoreMizo/fmtconv#7]
Dear Laurent,

I would like to request a feature.  Can you add the capability to do UHD compliant Standard Dynamic Range (SDR) to High Dynamic Range (HDR) conversion (and also the opposite HDR to SDR conversion) to Fmtconv plugin?

I also sent you a long email with all the technical research that I could find.  In summary, the required new features are listed below.  

1) A custom HDR-1000 system compatible SMPTE ST 2084 transfer function that maps to "0 cd/m2 to 1000 cd/m2" luminance range. (Note: current 2084 function included in Fmtconv maps to 0 to 10,000 cd/m2) 

2) Add DCI-P3 color primaries as a preset to primaries function.  This is not very urgent since "gd=[0.265, 0.69], bd=[0.15, 0.06], rd=[0.68, 0.32], wd=[0.3127, 0.329]" command can be used to manually define DCI-P3 primaries in fmtconv r18.

Once these two new features  are implemented, the workflow in Fmtconv will be the following for SDR to HDR conversion.
-Convert source video to "Linear light RGB 4:4:4"
-If necessary, change primaries to one of the HDR compatible primaries (BT709, BT2020, or DCI-P3)
-Convert transfer function from Linear to the custom SMPTE ST 2084 that maps to "0 to 1000 cd/m2" luminance range
-Resample to YUV 4:2:0 10 bit using BT2020 or BT709 matrix (which ever matrix is appropriate)
-Send YUV to x265 encoder.  Specify the 2084 transfer fuction, appropriate matrix and appropriate primaries in the x265 command line.

The opposite steps can be used to convert HDR to SDR.

Please let me know what you think.

Best Regards

**Comment by J1Man** [comment]
P.S.  I just saw your Doom9 forum thread.  I signed up for Doom9 but it does not let me post until I have been registered for 5 days.  I will post there 5 days later.

**Comment by benmanw** [comment]
I carried it to Doom9.

**Comment by J1Man** [comment]
Dear Benmanw,

Thanks for moving the message to Doom9.  I won't be able to post on Doom9 until I have been registered for 5 days (until 3/19/2016).  I would appreciate if you can also move the following message along with the source code patches that I generated.

I attached the source code patch zip file for fmtconv r18 that modifies SMPTE-ST-2084 function to "0 cd/m2 to 1000 cd/m2" luminance range and adds the "dci-p3" preset to primaries function. I also attached a zip file that contains the complete fmtconv r18 source code that is already patched.  I would appreciate if somebody with Visual Studio can compile the 64bit fmtconv.dll for Windows 7.  No matter how hard I tried in the last 2 days, I could not compile fmtconv.dll on Windows 7 by using MSYS2 and mingw64.

I saw that fmtconv uses the "Dolby Labs recommended version of SMPTE-ST-2084 function" specified on page 17/58 of the following PDF document.  
http://www.mediaandbroadcast.bt.com/wp-content/uploads/D2936-UHDTV-final.pdf

I think that was good choice because Dolby Labs version is designed for easy scalability between luminance ranges.  Upper bound of the range can be changed by dividing or multiplying the right hand side of the function shown on page 17/58 of the PDF document.  That's how I modified lines 78 and 83 of the TransOp2084.cpp file.

I added "dci-p3" primaries preset after line 356 of Primaries.cpp function.

[fmtconv-r18-HDR1000-patch-only.zip](https://github.com/EleonoreMizo/fmtconv/files/175990/fmtconv-r18-HDR1000-patch-only.zip)
[fmtconv-r18-patched-with-HDR1000features.zip](https://github.com/EleonoreMizo/fmtconv/files/175991/fmtconv-r18-patched-with-HDR1000features.zip)

Best Regards

**Comment by sl1pkn07** [comment]
that patchset is linux compatible?

greetings

**Comment by myrsloik** [comment]
This is only about the range. But why can't you simply modify it with Expr? All you've added on that side is a simple multiplication.

**Comment by J1Man** [comment]
Dear sl1pkn07,

I do not have linux.  I only have Windows 7. Having said that, in theory the patch should be compatible with all platforms (including linux) that fmtconv currently supports since the changes I made are very minor. For SMPTE-ST-2084 function there are only two lines of multiplication changes.  For the primaries there are 7 lines added for "dci-p3" preset that follow the exact same preset format that fmtconv author used for other presets.

**Comment by J1Man** [comment]
Dear Myrsloik,

Thanks for the feedback.  How can I change the luminance mapping range of Fmtconv's  SMPTE-ST-2084 function from the original "0 cd/m2 to 10000 cd/m2" range to the desired "0 cd/m2 to 1000 cd/m2" range by using Expr function?  Please let me know.  That would be very useful to me.


The main reason why I created the patch is to clearly show which modification is necessary to fmtconv's SMPTE-ST-2084 function for HDR1000 compatibility.  All that is needed for HDR1000 compatibility is a very very simple multiplication change in the source code (as you also pointed out by examining the changes I made).  If I just pointed Laurent to the PDF file with Dolby Labs SMPTE-ST-2084 formula and asked him to figure out how to make the changes, it would take him much much longer to figure out what he needs to change.

Laurent's final implementation will probably be different.  As I said in my message, instead of hard coding the upper bound of the range into the function (as I did in my patch), it is better to have the ability to play with it. He will probably find a good way to accept the upper bound (or an upper bound multiplier) for the luminance range as an input to SMPTE-ST-2084 function.  I don't have enough programming experience to make major changes like that in the source code.

**Comment by myrsloik** [comment]
Simple multiplication by 10 for everything. This way you can do it without modifying fmtconv itself
clip = core.std.Expr(clip, expr="x 10 *")

**Comment by EleonoreMizo** [comment]
– I added the DCI-P3 preset to `primaries` → 22cefbc055785aa69f497a300ab7b2827cecc4d3
– Use `cont=1000.0/10000.0` in `transfer` when converting from a transfer characteristic where 1.0 represents 1000 cd/m² to the ST 2084 characteristic.
